/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package cr.uned.ac.proyectotriage.view;

import cr.uned.ac.proyectotriage.dao.PacienteDAO;
import cr.uned.ac.proyectotriage.dominio.Paciente;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * 
 */
public class RegistroPacientes extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(RegistroPacientes.class.getName());

    /**
     * Creates new form RegistroPacientes
     */
    public RegistroPacientes() {
        initComponents();
        
        nivel_dolor_slider.setMinimum(1);
        nivel_dolor_slider.setMaximum(10);
        nivel_dolor_slider.setValue(1);          
        nivel_dolor_slider.setMajorTickSpacing(1);
        nivel_dolor_slider.setPaintTicks(true);  
        nivel_dolor_slider.setPaintLabels(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        nombre_lbl = new javax.swing.JLabel();
        nombre_completo_txtf = new javax.swing.JTextField();
        edad_lbl = new javax.swing.JLabel();
        edad_txtf = new javax.swing.JTextField();
        consulta_lbl = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        consulta_txta = new javax.swing.JTextArea();
        freq_lbl = new javax.swing.JLabel();
        freq_txtf = new javax.swing.JTextField();
        temp_lbl = new javax.swing.JLabel();
        temp_txtf = new javax.swing.JTextField();
        nivel_dolor_slider = new javax.swing.JSlider();
        nivel_dolor_lbl = new javax.swing.JLabel();
        registar_btn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Registro de Pacientes");

        nombre_lbl.setText("Nombre completo:");

        edad_lbl.setText("Edad:");

        consulta_lbl.setText("Motivo de Consulta: ");

        consulta_txta.setColumns(20);
        consulta_txta.setRows(5);
        jScrollPane1.setViewportView(consulta_txta);

        freq_lbl.setText("Frecuencia Cardiaca (lpm): ");

        temp_lbl.setText("Temperatura Corporal (°C): ");

        nivel_dolor_slider.setMaximum(10);
        nivel_dolor_slider.setMinimum(1);
        nivel_dolor_slider.setMinorTickSpacing(10);
        nivel_dolor_slider.setPaintLabels(true);
        nivel_dolor_slider.setPaintTicks(true);

        nivel_dolor_lbl.setText("Nivel de Dolor: ");

        registar_btn.setText("Registrar Paciente");
        registar_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registar_btnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(390, 390, 390)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(163, 163, 163)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nombre_lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(edad_lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(consulta_lbl)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(temp_lbl)
                                .addComponent(freq_lbl, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(nivel_dolor_lbl, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nombre_completo_txtf, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(edad_txtf, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(temp_txtf, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 134, Short.MAX_VALUE)
                                .addComponent(freq_txtf, javax.swing.GroupLayout.Alignment.LEADING))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(registar_btn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(nivel_dolor_slider, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)))))
                .addContainerGap(263, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(nivel_dolor_lbl)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nombre_lbl)
                            .addComponent(nombre_completo_txtf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(edad_lbl)
                            .addComponent(edad_txtf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(consulta_lbl)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(46, 46, 46)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(temp_lbl)
                            .addComponent(temp_txtf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(freq_lbl)
                            .addComponent(freq_txtf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(44, 44, 44)
                        .addComponent(nivel_dolor_slider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(33, 33, 33)
                .addComponent(registar_btn)
                .addContainerGap(37, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void registar_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registar_btnActionPerformed
        // TODO add your handling code here:
        
        
        
        String nombre_completo = nombre_completo_txtf.getText().trim(); // se obtiene el string del campo de texto de nombre completo
        
        String edad = edad_txtf.getText().trim(); // se obtiene el string del campo de texto de edad
        
        String motivo_consulta = consulta_txta.getText().trim(); // se obtiene el string del text area 
        
        String temperatura = temp_txtf.getText().trim();
        
        String frequencia = freq_txtf.getText().trim();
        
        if(nombre_completo.isEmpty() || edad.isEmpty() ||  motivo_consulta.isEmpty() || temperatura.isEmpty() || frequencia.isEmpty()){
            JOptionPane.showMessageDialog(this, "Error al registrar un nuevo paciente, revise que los campos esten debidamente completos", "Registro Paciente", JOptionPane.ERROR_MESSAGE);
        }else{
            
            int edad_paciente = Integer.parseInt(edad); // se convierte el string en un número entero para poder ser guardado por el DAO
        
            double temperatura_paciente = Double.parseDouble(temperatura); // se convierte el string de temperatura en un número decimal para ser guardado por el DAO

            double frequencia_paciente = Double.parseDouble(frequencia); // se convierte el string de frequencia en un número entero decimal para ser guardado por el dao

            int nivel_dolor = nivel_dolor_slider.getValue();

            
            
            if(edad_paciente<0 || temperatura_paciente > 45){
                JOptionPane.showMessageDialog(this, "Error al registrar un nuevo paciente, edad no puede ser negativa, ni fiebre puede ser mayor a 45 °C", "Registro Paciente", JOptionPane.ERROR_MESSAGE);
            }else{
                String clasificacion = "";
                String color = "";

                if(nivel_dolor >= 8 || frequencia_paciente >= 120 || temperatura_paciente >= 39.0 ){
                    clasificacion = "Emergencia";
                    color = "Rojo";
                }else if((nivel_dolor >= 5 &&  nivel_dolor <= 7) || (frequencia_paciente >= 100 &&  frequencia_paciente <= 119) || (temperatura_paciente >= 37.5 && temperatura_paciente <= 38.9 )){
                    clasificacion = "Atención Prioritaria";
                    color = "Amarillo";
                }else{
                    clasificacion = "Atención Normal";
                    color = "Verde";
                }

                Paciente nuevo_paciente = new Paciente(nombre_completo, edad_paciente, motivo_consulta, temperatura_paciente, frequencia_paciente, nivel_dolor, clasificacion,color);

                PacienteDAO pacienteDAO = new PacienteDAO();
                try {
                    pacienteDAO.insertarPaciente(nuevo_paciente);
                    JOptionPane.showMessageDialog(this, "Paciente registrado con exito!", "Registro Paciente", JOptionPane.INFORMATION_MESSAGE);

                } catch (Exception ex) {
                    ex.printStackTrace();
                    JOptionPane.showMessageDialog(this, "Error al registrar un nuevo paciente, intente de nuevo", "Registro Paciente", JOptionPane.ERROR_MESSAGE);
                }

                nombre_completo_txtf.setText("");
                edad_txtf.setText("");
                consulta_txta.setText("");
                temp_txtf.setText("");
                freq_txtf.setText("");
                nivel_dolor_slider.setValue(1);
                }

        }
        
        
        
    }//GEN-LAST:event_registar_btnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new RegistroPacientes().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel consulta_lbl;
    private javax.swing.JTextArea consulta_txta;
    private javax.swing.JLabel edad_lbl;
    private javax.swing.JTextField edad_txtf;
    private javax.swing.JLabel freq_lbl;
    private javax.swing.JTextField freq_txtf;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel nivel_dolor_lbl;
    private javax.swing.JSlider nivel_dolor_slider;
    private javax.swing.JTextField nombre_completo_txtf;
    private javax.swing.JLabel nombre_lbl;
    private javax.swing.JButton registar_btn;
    private javax.swing.JLabel temp_lbl;
    private javax.swing.JTextField temp_txtf;
    // End of variables declaration//GEN-END:variables
}
