/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package cr.uned.ac.proyectotriage.view;

import cr.uned.ac.proyectotriage.view.RegistroPacientes;
import cr.uned.ac.proyectotriage.view.VisualizacionPacientes;
import java.awt.Container;
import java.awt.Image;
import java.net.URL;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;


/**
 *
 */
public class ViewPrincipal extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ViewPrincipal.class.getName());

    /**
     * Creates new form ViewPrincipal
     */
    public ViewPrincipal() {
        initComponents();
        
        URL url = getClass().getResource("/cr/uned/ac/proyectotriage/recursos/triage.png"); //se trae la ruta de la imagen para la vista principal
 
        initComponents();//inicializa los componentes del formulario 
        ImageIcon label_icon = new ImageIcon(getClass().getResource("/cr/uned/ac/proyectotriage/recursos/triage.png"));
        Image scaledImage = label_icon.getImage().getScaledInstance(
        icon_lbl.getWidth(), 
        icon_lbl.getHeight(), 
        Image.SCALE_SMOOTH
    );// obtiene la información de la imagen, le da nuevo tamaño a la imagen y pone la imagen en un label 
        
        icon_lbl.setIcon(new ImageIcon(scaledImage)); //pone la imagen en el label de vista login
    
        
        setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);

        addWindowListener(new java.awt.event.WindowAdapter() {
        @Override
        public void windowClosing(java.awt.event.WindowEvent e) {
            confirmarSalida();
        }
        });
    }
    
    
    public void confirmarSalida() {
        int choice = JOptionPane.showConfirmDialog(
            this,
            "Esta seguro de que quiere salir del programa?",
            "Confirmación de Salida",
            JOptionPane.YES_NO_OPTION,
            JOptionPane.QUESTION_MESSAGE
        );

        if (choice == JOptionPane.YES_OPTION) {
            System.exit(0); 
        }
}


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        registro_pacientes_btn = new javax.swing.JButton();
        visualizacion_pacientes_btn = new javax.swing.JButton();
        icon_lbl = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Sistema de Triage ");

        jLabel2.setText("Seleccione una acción:");

        registro_pacientes_btn.setText("Registro de Pacientes");
        registro_pacientes_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registro_pacientes_btnActionPerformed(evt);
            }
        });

        visualizacion_pacientes_btn.setText("Visualización de Pacientes");
        visualizacion_pacientes_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                visualizacion_pacientes_btnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(icon_lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(44, 44, 44)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(registro_pacientes_btn)
                            .addComponent(jLabel2)
                            .addComponent(visualizacion_pacientes_btn)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(319, 319, 319)
                        .addComponent(jLabel1)))
                .addContainerGap(164, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(jLabel1)
                .addGap(74, 74, 74)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(53, 53, 53)
                        .addComponent(registro_pacientes_btn)
                        .addGap(40, 40, 40)
                        .addComponent(visualizacion_pacientes_btn))
                    .addComponent(icon_lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(151, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void visualizacion_pacientes_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_visualizacion_pacientes_btnActionPerformed
        // TODO add your handling code here:
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                VisualizacionPacientes vistaVisPacientes = new VisualizacionPacientes();
                vistaVisPacientes.setVisible(true);
                vistaVisPacientes.setLocationRelativeTo(null); //centra la ventana 
                vistaVisPacientes.setResizable(false);
            }
          });
    }//GEN-LAST:event_visualizacion_pacientes_btnActionPerformed

    private void registro_pacientes_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registro_pacientes_btnActionPerformed
        // TODO add your handling code here:
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                RegistroPacientes vistaRegPacientes = new RegistroPacientes();
                vistaRegPacientes.setVisible(true);
                vistaRegPacientes.setLocationRelativeTo(null); //centra la ventana 
                vistaRegPacientes.setResizable(false);
            }
          });
    }//GEN-LAST:event_registro_pacientes_btnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new ViewPrincipal().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel icon_lbl;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton registro_pacientes_btn;
    private javax.swing.JButton visualizacion_pacientes_btn;
    // End of variables declaration//GEN-END:variables
}
